Added hack to support search mode in IE11
maslianok/react-select-me pull request #3
Opened 2017-02-01 13:53 UTC by zlumyo

IE11 doesn't support `input` event ([proof](https://developer.mozilla.org/en-US/docs/Web/Events/input))
So, in React it doesn't support onInput event for `contenteditable` elements.

2017-02-01 14:04 UTC, maslianok requested changes

2017-02-01 14:04 UTC, maslianok commented on src/ReactSelectMe.js
> +          if (false || !!document.documentMode) this.onSearch(e);
`false` is always false, isn't it? :) Can we get rid of it?

I would also suggest you move this logic to the `onSearch` method.

So here you will have 
```
onKeyUp={this.onSearch}
```

And inside the `onSearch` method:
```javascript
onSearch = (evt) => {
  if (evt.type === 'keyup' && !!document.documentMode) {
    return;
  }
  // ...
```

2017-02-02 05:35 UTC, zlumyo commented on src/ReactSelectMe.js
> +          if (false || !!document.documentMode) this.onSearch(e);
I had some research about `false` in IE checking condition.
Special comment `/*@cc_on!@*/`, which prepends it, is a fuature of IE 6-10. So this `false` is unneccessary for IE11 checking.

2017-02-02 06:06 UTC, maslianok commented
@zlumyo Great job! Thanks!

2017-02-02 06:06 UTC, maslianok approved these changes

2017-02-02 06:07 UTC, merged